name: YOLO Flask API CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Static Application Security Testing (SAST)
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.9'

      - name: Install Bandit (SAST)
        run: pip install bandit

      - name: Run Bandit Security Scan & Save Report
        run: bandit -r app/ -f json -o bandit-report.json || true
  
      - name: Upload SAST Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SAST-Bandit-Report
          path: bandit-report.json


  # Build and Push Docker Image to GitHub Container Registry
  build_and_push:
    needs: security_scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/YOUR_USERNAME/yolo-flask-api:latest .

      - name: Push Image to GitHub Container Registry
        run: docker push ghcr.io/YOUR_USERNAME/yolo-flask-api:latest

  # Deploy to DigitalOcean via SSH
  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into DigitalOcean & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /root/yolo-flask-api
            git pull origin main
            docker pull ghcr.io/YOUR_USERNAME/yolo-flask-api:latest
            docker stop yolo-api || true
            docker rm yolo-api || true
            docker run -d -p 5001:5001 --name yolo-api ghcr.io/YOUR_USERNAME/yolo-flask-api:latest
